// <auto-generated />

using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

// General Information about an assembly is controlled through the following 
// set of attributes. Change these attribute values to modify the information
// associated with an assembly.
[assembly: AssemblyTitle("msile")]
[assembly: AssemblyDescription("Package Manager for Windows")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("Camilo Martin")]
[assembly: AssemblyProduct("msile")]
[assembly: AssemblyCopyright("GNU GPL v3")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]

// Setting ComVisible to false makes the types in this assembly not visible 
// to COM components.  If you need to access a type in this assembly from 
// COM, set the ComVisible attribute to true on that type.
[assembly: ComVisible(false)]

// The following GUID is for the ID of the typelib if this project is exposed to COM
[assembly: Guid("cf2e2ae5-6306-4533-a86c-d4d561b5bb4d")]

// Version information for an assembly consists of the following four values:
//
//      Major Version
//      Minor Version 
//      Build Number
//      Revision
//
// You can specify all the values or you can default the Build and Revision Numbers 
// by using the '*' as shown below:
// [assembly: AssemblyVersion("1.0.*")]
[assembly: AssemblyVersion("0.1.43")]
[assembly: AssemblyFileVersion("0.1.43")]
[assembly: NeutralResourcesLanguageAttribute("en")]
